import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { ProductOptionOrderByWithRelationInputObjectSchema as ProductOptionOrderByWithRelationInputObjectSchema } from './objects/ProductOptionOrderByWithRelationInput.schema';
import { ProductOptionWhereInputObjectSchema as ProductOptionWhereInputObjectSchema } from './objects/ProductOptionWhereInput.schema';
import { ProductOptionWhereUniqueInputObjectSchema as ProductOptionWhereUniqueInputObjectSchema } from './objects/ProductOptionWhereUniqueInput.schema';
import { ProductOptionCountAggregateInputObjectSchema as ProductOptionCountAggregateInputObjectSchema } from './objects/ProductOptionCountAggregateInput.schema';
import { ProductOptionMinAggregateInputObjectSchema as ProductOptionMinAggregateInputObjectSchema } from './objects/ProductOptionMinAggregateInput.schema';
import { ProductOptionMaxAggregateInputObjectSchema as ProductOptionMaxAggregateInputObjectSchema } from './objects/ProductOptionMaxAggregateInput.schema';
import { ProductOptionAvgAggregateInputObjectSchema as ProductOptionAvgAggregateInputObjectSchema } from './objects/ProductOptionAvgAggregateInput.schema';
import { ProductOptionSumAggregateInputObjectSchema as ProductOptionSumAggregateInputObjectSchema } from './objects/ProductOptionSumAggregateInput.schema';

export const ProductOptionAggregateSchema: z.ZodType<Prisma.ProductOptionAggregateArgs> = z.object({ orderBy: z.union([ProductOptionOrderByWithRelationInputObjectSchema, ProductOptionOrderByWithRelationInputObjectSchema.array()]).optional(), where: ProductOptionWhereInputObjectSchema.optional(), cursor: ProductOptionWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), ProductOptionCountAggregateInputObjectSchema ]).optional(), _min: ProductOptionMinAggregateInputObjectSchema.optional(), _max: ProductOptionMaxAggregateInputObjectSchema.optional(), _avg: ProductOptionAvgAggregateInputObjectSchema.optional(), _sum: ProductOptionSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.ProductOptionAggregateArgs>;

export const ProductOptionAggregateZodSchema = z.object({ orderBy: z.union([ProductOptionOrderByWithRelationInputObjectSchema, ProductOptionOrderByWithRelationInputObjectSchema.array()]).optional(), where: ProductOptionWhereInputObjectSchema.optional(), cursor: ProductOptionWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), ProductOptionCountAggregateInputObjectSchema ]).optional(), _min: ProductOptionMinAggregateInputObjectSchema.optional(), _max: ProductOptionMaxAggregateInputObjectSchema.optional(), _avg: ProductOptionAvgAggregateInputObjectSchema.optional(), _sum: ProductOptionSumAggregateInputObjectSchema.optional() }).strict();