import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { CouponRedemptionOrderByWithRelationInputObjectSchema as CouponRedemptionOrderByWithRelationInputObjectSchema } from './objects/CouponRedemptionOrderByWithRelationInput.schema';
import { CouponRedemptionWhereInputObjectSchema as CouponRedemptionWhereInputObjectSchema } from './objects/CouponRedemptionWhereInput.schema';
import { CouponRedemptionWhereUniqueInputObjectSchema as CouponRedemptionWhereUniqueInputObjectSchema } from './objects/CouponRedemptionWhereUniqueInput.schema';
import { CouponRedemptionCountAggregateInputObjectSchema as CouponRedemptionCountAggregateInputObjectSchema } from './objects/CouponRedemptionCountAggregateInput.schema';
import { CouponRedemptionMinAggregateInputObjectSchema as CouponRedemptionMinAggregateInputObjectSchema } from './objects/CouponRedemptionMinAggregateInput.schema';
import { CouponRedemptionMaxAggregateInputObjectSchema as CouponRedemptionMaxAggregateInputObjectSchema } from './objects/CouponRedemptionMaxAggregateInput.schema';

export const CouponRedemptionAggregateSchema: z.ZodType<Prisma.CouponRedemptionAggregateArgs> = z.object({ orderBy: z.union([CouponRedemptionOrderByWithRelationInputObjectSchema, CouponRedemptionOrderByWithRelationInputObjectSchema.array()]).optional(), where: CouponRedemptionWhereInputObjectSchema.optional(), cursor: CouponRedemptionWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), CouponRedemptionCountAggregateInputObjectSchema ]).optional(), _min: CouponRedemptionMinAggregateInputObjectSchema.optional(), _max: CouponRedemptionMaxAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.CouponRedemptionAggregateArgs>;

export const CouponRedemptionAggregateZodSchema = z.object({ orderBy: z.union([CouponRedemptionOrderByWithRelationInputObjectSchema, CouponRedemptionOrderByWithRelationInputObjectSchema.array()]).optional(), where: CouponRedemptionWhereInputObjectSchema.optional(), cursor: CouponRedemptionWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), CouponRedemptionCountAggregateInputObjectSchema ]).optional(), _min: CouponRedemptionMinAggregateInputObjectSchema.optional(), _max: CouponRedemptionMaxAggregateInputObjectSchema.optional() }).strict();