import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { ProductOptionValueOrderByWithRelationInputObjectSchema as ProductOptionValueOrderByWithRelationInputObjectSchema } from './objects/ProductOptionValueOrderByWithRelationInput.schema';
import { ProductOptionValueWhereInputObjectSchema as ProductOptionValueWhereInputObjectSchema } from './objects/ProductOptionValueWhereInput.schema';
import { ProductOptionValueWhereUniqueInputObjectSchema as ProductOptionValueWhereUniqueInputObjectSchema } from './objects/ProductOptionValueWhereUniqueInput.schema';
import { ProductOptionValueCountAggregateInputObjectSchema as ProductOptionValueCountAggregateInputObjectSchema } from './objects/ProductOptionValueCountAggregateInput.schema';

export const ProductOptionValueCountSchema: z.ZodType<Prisma.ProductOptionValueCountArgs> = z.object({ orderBy: z.union([ProductOptionValueOrderByWithRelationInputObjectSchema, ProductOptionValueOrderByWithRelationInputObjectSchema.array()]).optional(), where: ProductOptionValueWhereInputObjectSchema.optional(), cursor: ProductOptionValueWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), select: z.union([ z.literal(true), ProductOptionValueCountAggregateInputObjectSchema ]).optional() }).strict() as unknown as z.ZodType<Prisma.ProductOptionValueCountArgs>;

export const ProductOptionValueCountZodSchema = z.object({ orderBy: z.union([ProductOptionValueOrderByWithRelationInputObjectSchema, ProductOptionValueOrderByWithRelationInputObjectSchema.array()]).optional(), where: ProductOptionValueWhereInputObjectSchema.optional(), cursor: ProductOptionValueWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), select: z.union([ z.literal(true), ProductOptionValueCountAggregateInputObjectSchema ]).optional() }).strict();