import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { ProductOptionValueWhereInputObjectSchema as ProductOptionValueWhereInputObjectSchema } from './objects/ProductOptionValueWhereInput.schema';
import { ProductOptionValueOrderByWithAggregationInputObjectSchema as ProductOptionValueOrderByWithAggregationInputObjectSchema } from './objects/ProductOptionValueOrderByWithAggregationInput.schema';
import { ProductOptionValueScalarWhereWithAggregatesInputObjectSchema as ProductOptionValueScalarWhereWithAggregatesInputObjectSchema } from './objects/ProductOptionValueScalarWhereWithAggregatesInput.schema';
import { ProductOptionValueScalarFieldEnumSchema } from './enums/ProductOptionValueScalarFieldEnum.schema';
import { ProductOptionValueCountAggregateInputObjectSchema as ProductOptionValueCountAggregateInputObjectSchema } from './objects/ProductOptionValueCountAggregateInput.schema';
import { ProductOptionValueMinAggregateInputObjectSchema as ProductOptionValueMinAggregateInputObjectSchema } from './objects/ProductOptionValueMinAggregateInput.schema';
import { ProductOptionValueMaxAggregateInputObjectSchema as ProductOptionValueMaxAggregateInputObjectSchema } from './objects/ProductOptionValueMaxAggregateInput.schema';

export const ProductOptionValueGroupBySchema: z.ZodType<Prisma.ProductOptionValueGroupByArgs> = z.object({ where: ProductOptionValueWhereInputObjectSchema.optional(), orderBy: z.union([ProductOptionValueOrderByWithAggregationInputObjectSchema, ProductOptionValueOrderByWithAggregationInputObjectSchema.array()]).optional(), having: ProductOptionValueScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(ProductOptionValueScalarFieldEnumSchema), _count: z.union([ z.literal(true), ProductOptionValueCountAggregateInputObjectSchema ]).optional(), _min: ProductOptionValueMinAggregateInputObjectSchema.optional(), _max: ProductOptionValueMaxAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.ProductOptionValueGroupByArgs>;

export const ProductOptionValueGroupByZodSchema = z.object({ where: ProductOptionValueWhereInputObjectSchema.optional(), orderBy: z.union([ProductOptionValueOrderByWithAggregationInputObjectSchema, ProductOptionValueOrderByWithAggregationInputObjectSchema.array()]).optional(), having: ProductOptionValueScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(ProductOptionValueScalarFieldEnumSchema), _count: z.union([ z.literal(true), ProductOptionValueCountAggregateInputObjectSchema ]).optional(), _min: ProductOptionValueMinAggregateInputObjectSchema.optional(), _max: ProductOptionValueMaxAggregateInputObjectSchema.optional() }).strict();